FROM public.ecr.aws/docker/library/openjdk:11.0.16

ENV ANDROID_HOME /opt/android-sdk
ENV FLUTTER_ROOT="/opt/flutter"
ENV PATH $ANDROID_HOME/platform-tools:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:${FLUTTER_ROOT}/bin:${FLUTTER_ROOT}/bin/cache/dart-sdk/bin:${PATH}

RUN apt-get update && apt-get install -y wget unzip
RUN wget --quiet --output-document=android-sdk.zip https://dl.google.com/android/repository/sdk-tools-linux-4333796.zip && \
  unzip android-sdk.zip -d /opt/android-sdk && \
  rm android-sdk.zip

RUN wget -q https://dl.google.com/android/repository/commandlinetools-linux-8512546_latest.zip -O android-commandline-tools.zip \
    && mkdir -p /opt/android-sdk/cmdline-tools \
    && unzip -q android-commandline-tools.zip -d /tmp/ \
    && mv /tmp/cmdline-tools/ /opt/android-sdk/cmdline-tools/latest \
    && rm android-commandline-tools.zip && ls -la /opt/android-sdk/cmdline-tools/latest/

ENV ANDROID_SDK_VERSION="30.0.3"
ENV ANDROID_PLATFORM_VERSION="31"
ENV FLUTTER_VERSION="3.10.3"
ENV LCOV_VERSION="v1.15"

RUN mkdir -p $ANDROID_HOME/tools/jaxb_lib
RUN wget https://repo1.maven.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar -O $ANDROID_HOME/tools/jaxb_lib/activation.jar && \
    wget https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.3/jaxb-impl-2.3.3.jar -O $ANDROID_HOME/tools/jaxb_lib/jaxb-impl.jar && \
    wget https://repo1.maven.org/maven2/com/sun/istack/istack-commons-runtime/3.0.11/istack-commons-runtime-3.0.11.jar -O $ANDROID_HOME/tools/jaxb_lib/istack-commons-runtime.jar && \
    wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-xjc/2.3.3/jaxb-xjc-2.3.3.jar -O $ANDROID_HOME/tools/jaxb_lib/jaxb-xjc.jar && \
    wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar -O $ANDROID_HOME/tools/jaxb_lib/jaxb-core.jar && \
    wget https://repo1.maven.org/maven2/org/glassfish/jaxb/jaxb-jxc/2.3.3/jaxb-jxc-2.3.3.jar -O $ANDROID_HOME/tools/jaxb_lib/jaxb-jxc.jar && \
    wget https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar -O $ANDROID_HOME/tools/jaxb_lib/jaxb-api.jar
# Append jaxb_lib to the CLASSPATH in sdkmanager and avdmanager
RUN sed -ie 's%^CLASSPATH=.*%\0:$APP_HOME/jaxb_lib/*%' $ANDROID_HOME/tools/bin/sdkmanager $ANDROID_HOME/tools/bin/avdmanager

# Install Android Build Tool and Libraries
RUN echo y | sdkmanager "build-tools;${ANDROID_SDK_VERSION}" "platforms;android-${ANDROID_PLATFORM_VERSION}" "platform-tools"

RUN apt-get update && apt-get install -y git

# Install lcov
RUN git clone --branch $LCOV_VERSION --depth=1 https://github.com/linux-test-project/lcov.git /bin/lcov

# Install Flutter.
RUN git clone --branch $FLUTTER_VERSION --depth=1 https://github.com/flutter/flutter "${FLUTTER_ROOT}"

# Disable analytics and crash reporting on the builder.
#RUN flutter config  --no-analytics

# Perform an artifact precache so that no extra assets need to be downloaded on demand.
#RUN flutter precache

# Accept licenses.
#RUN yes "y" | flutter doctor --android-licenses

# Perform a doctor run.
#RUN flutter doctor -v

ENTRYPOINT [ "/bin/bash", "-c" ]
