#!/usr/bin/env bash


set -e
set -o pipefail

# source: git@gitlab.tools.buk0.com:tools/go-helpers/gosonar.git
# source gosonar
SONAR_SCANNER_CLI_DOCKER_IMAGE="sonarsource/sonar-scanner-cli:4.7.0"

ECR_URL="688318228301.dkr.ecr.ap-southeast-1.amazonaws.com"
FLUTTER_IMAGE="${ECR_URL}/superapp-apollo/apl-flutter"

COVERAGE_TARGET=0
VERSION=1.0

TASK=$1
ARGS=${@:2}
PROJECT_NAME="mkp-line-mini"

runs_inside_gocd() {
  test -n "${GO_JOB_NAME}"
}

docker_ensure_volume() {
  docker volume inspect $1 >/dev/null 2>&1 || docker volume create $1 >/dev/null 2>&1
}

docker_run() {
  (
  local AWS_ACCESS_KEY_ID_prev="${AWS_ACCESS_KEY_ID}"
  local AWS_SECRET_ACCESS_KEY_prev="${AWS_SECRET_ACCESS_KEY}"
  local AWS_SESSION_TOKEN_prev="${AWS_SESSION_TOKEN}"

  if runs_inside_gocd ; then
    aws ecr get-login --no-include-email --region ap-southeast-1 | bash
  else #for new aws cli
    aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin ${ECR_URL}
  fi

  if [[ -z "${DOCKER_IMAGE}" ]]; then
    echo -n "Building toolchain container; this might take a while..."
    DOCKER_IMAGE=$(docker build -f ${DOCKERFILE} . -q)
    echo " Done."
  else
    docker pull ${DOCKER_IMAGE}
  fi

  export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID_prev}"
  export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY_prev}"
  export AWS_SESSION_TOKEN="${AWS_SESSION_TOKEN_prev}"

  if runs_inside_gocd; then
    local args="-v godata:/godata -w $(pwd)"
  else
    local args="-it -v $(pwd):/workspace -w /workspace"
  fi
  echo -n "Running the task in the docker ${DOCKER_IMAGE}"
  DOCKER_ARGS="${DOCKER_ARGS} -v ${HOME}/.aws:/root/.aws"
  docker run --rm \
             --hostname $(hostname) \
             --env-file <(env | grep GO_) \
             --env-file <(env | grep AWS_) \
             --env-file <(env | grep SUPERAPP_) \
             ${args} ${DOCKER_ARGS} ${DOCKER_IMAGE} "$@"
  )
}

flutter_app() {
  DOCKER_IMAGE="${FLUTTER_IMAGE}"

  docker_ensure_volume superapp-gradle-cache
  docker_ensure_volume sonarqube-cache
  SSH_ARGS="-v ${HOME}/.ssh:/root/.ssh:cached"
  GRADLE_CACHE_ARGS="-v superapp-gradle-cache:/root/.gradle"
  SONARQUBE_CACHE_ARGS="-v sonarqube-cache:/root/.sonar/cache"
  FLUTTER_CACHE="-v ${HOME}/.pub-cache:/root/.pub-cache"
  DOCKER_ARGS="$DOCKER_ARGS $SSH_ARGS $GRADLE_CACHE_ARGS $SONARQUBE_CACHE_ARGS $FLUTTER_CACHE -v /var/run/secrets/eks.amazonaws.com/serviceaccount/:/var/run/secrets/eks.amazonaws.com/serviceaccount/ -v $(pwd):$(pwd) -w $(pwd)"
  for mod in $(env | grep NON_); do
    DOCKER_ARGS="${DOCKER_ARGS} -e ${mod}"
  done
  echo "${DOCKER_ARGS}"

  docker_run $@
}

help__build_web="Run build web"
task_build_web() {
  if runs_inside_gocd; then
    local environment=$1
    flutter_app flutter pub get
    flutter_app flutter build web --dart-define=SET_ENV=$1
  else
    flutter pub get
    flutter build web --dart-define=SET_ENV=$1
  fi
}

account_for_env() {
  case $1 in
      'dev') echo "dev";;
      'qa') echo "qa";;
      'int') echo "int";;
      'uat') echo "uat";;
      'prod') echo "prod";;
  esac
}

distribution_secret_env() {
  case $1 in
      'dev') echo "EQ3OEEMS01F45";;
      'qa') echo "xxxxx";;
      'uat') echo "xxxxxx";;
  esac
}

portal_account_id_for_name() {
  case $1 in
      'dev') echo "308631386256";;
      'qa') echo "308631386256";;
      'uat') echo "308631386256";;
      'prod') echo "308565014163";;
  esac
}

help__webDeploy="deploy web to s3"
task_webDeploy(){
  local environment=$1
  local distribution_secret=$(distribution_secret_env $environment)
  assume_role $(account_id_for_name "${environment}") "DeployApp"
  aws s3 sync ../build/marketplace s3://marketplace-dev-mkp-line-mini --delete

  echo "Cloudfront distribution ID is ${distribution_secret}. Doing Invalidation now..."
  assume_role $(portal_account_id_for_name "$environment") "Marketplace-SelfService"
  aws cloudfront create-invalidation --distribution-id $distribution_secret --paths "/*"
}

help__check_path="Check working directory path"
task_check_path() {
  pwd
  ls
}


help__check="Run analytics of source code"
task_check() {
  if runs_inside_gocd; then
    flutter_app flutter pub get
    flutter_app flutter analyze lib
  else
    flutter analyze lib
  fi
}

help__unit_test="Run a unit test"
task_unit_test() {
  if runs_inside_gocd; then
    flutter_app flutter pub get
    flutter_app flutter test test/unit_test
  else
    flutter pub get
    flutter test test/unit_test
  fi
}

help__ui_test="Run ui test (widget test)"
task_ui_test() {
  if runs_inside_gocd; then
    flutter_app flutter pub get
    flutter_app flutter test test/widget_test
  else
    flutter pub get
    flutter test test/widget_test
  fi
}

help__test_coverage="Run test coverage"
task_test_coverage() {
  if runs_inside_gocd; then
    flutter_app flutter test --coverage test
    flutter_app flutter test --machine --coverage test > coverage.output
    flutter_app perl bin/lcov --remove coverage/lcov.info 'lib/views/*' 'lib/shared/pages/widgets/*' 'lib/configs/routes/*' 'lib/core/*' 'lib/core/dio_utils/*' 'lib/core/interceptors/*' 'lib/core/analytic_manager/*' 'lib/core/base/*' 'lib/core/dio/*' 'lib/core/dio/dio_utils/*' 'lib/core/dio/interceptors/*' 'lib/core/feature/*' 'lib/core/providers/*' 'lib/core/pages/widgets/*'  -o coverage/new_lcov.info
    flutter_app perl bin/genhtml coverage/new_lcov.info -o coverage coverage/new_lcov.info >coverage_result.log
  else
    flutter test --coverage test
    flutter test --machine --coverage test > coverage.output
    perl bin/lcov --remove coverage/lcov.info 'lib/views/*' 'lib/shared/pages/widgets/*' 'lib/configs/routes/*' 'lib/core/*' 'lib/core/analytic_manager/*' 'lib/core/base/*' 'lib/core/dio/*' 'lib/core/dio_utils/*' 'lib/core/interceptors/*' 'lib/core/dio/dio_utils/*' 'lib/core/dio/interceptors/*' 'lib/core/feature/*' 'lib/core/providers/*' 'lib/core/pages/widgets/*'  -o coverage/new_lcov.info
    perl bin/genhtml coverage/new_lcov.info -o coverage coverage/new_lcov.info >coverage_result.log
  fi
  echo "[INFO] Checking coverage..."
  RESULT=$(cat coverage_result.log)
  echo $RESULT
  RESULT=$(echo $RESULT | grep -o "lines......:.*")
  ar=($RESULT)
  COVERAGE=${ar[1]}
  END_INDEX=$(echo ${#COVERAGE})
  COVERAGE=${COVERAGE:0:END_INDEX-1}
  COVERAGE=$(printf "%.0f" $COVERAGE)

  echo "[INFO] Target coverage = $COVERAGE_TARGET%"
  echo "[INFO] Coverage = $COVERAGE%"

  if [ $COVERAGE -ge $COVERAGE_TARGET ]; then
    echo "[INFO] Coverage passed."
  else
    echo "[ERROR] Coverage failed."
    rm coverage_result.log
    exit 1
  fi
  rm coverage_result.log

}

help__fmt="Fix lint format"
task_fmt() {
  if runs_inside_gocd; then
    flutter_app dart format lib -l 120
  else
    dart format lib -l 120
  fi
}

help__dependency_check="Run dependency check from sonarqube"
task_dependency_check() {
  flutter_app flutter pub get
  flutter_app flutter pub run dependency_validator
}

help__security_scan="Run dependency check from sonarqube"
task_security_scan() {
  export SONAR_LOGIN="fb824b9adc7e381f29b7b0b60b38cfdde9750104" 
  task_sonarScan
}

help__publish="Create new tag on git withb gocd counter ver"
task_publish() {
    echo "Version: $VERSION"
    local TAG_NAME=$VERSION.$GO_PIPELINE_COUNTER
    if [ -z "$(git ls-remote origin refs/tags/$TAG_NAME)" ]
    then
        git config --global user.email "ks-auto-bay+gocd-agent-user@thoughtworks.com"
        git config --global user.name "ks-auto-bay+gocd-agent-user"
        git tag -a $TAG_NAME -m "Auto publish on pipeline"
        git push origin $TAG_NAME
        echo "Publish success => $TAG_NAME"
        echo "MERCURY_VERSION=${TAG_NAME}" > mercury-version.info
    else
        echo "Tag name: $TAG_NAME already on origin"
    fi
}


sonar_app() {
  DOCKER_IMAGE="${SONAR_SCANNER_CLI_DOCKER_IMAGE}"

  DOCKER_ARGS="$DOCKER_ARGS -v /var/run/secrets/eks.amazonaws.com/serviceaccount/:/var/run/secrets/eks.amazonaws.com/serviceaccount/ -v $(pwd):$(pwd) -w $(pwd)"
  for mod in $(env | grep NON_); do
    DOCKER_ARGS="${DOCKER_ARGS} -e ${mod}"
  done
  echo "${DOCKER_ARGS}"

  docker_run $@
}

task_securityScanSonar() {
  DOCKER_ARGS="${DOCKER_ARGS} -e SONAR_HOST_URL=https://sonarqube.tools.buk0.com \
  -e SONAR_LOGIN=3ad23e205297c7f0e12a014686c2d1521851c6aa"
  sonar_app
}

help__assumeAgentRole="assume with specify agent role name [./go assumeAgentRole <agent role name>]"
task_assumeAgentRole() {
  local agent_role_name='tools-devsecops-cluster-marketplace-nonprod-agent-sa'
  local awsume_cache_folder="${HOME}/.awsume/cache"
  local cache_file="$awsume_cache_folder/aws-credentials-manual-sso"

  if test -d "$awsume_cache_folder" ; then
    echo "clearing $awsume_cache_folder"
    rm -rf $awsume_cache_folder
    mkdir $awsume_cache_folder
  fi
  
  echo "Assuming $agent_role_name.."
  local agent_role_creds=$(aws sts assume-role --role-arn "arn:aws:iam::688318228301:role/${agent_role_name}" --role-session-name $HOSTNAME)
  export AWS_SESSION_TOKEN=$(echo $agent_role_creds | jq -r .Credentials.SessionToken)
  export AWS_ACCESS_KEY_ID=$(echo $agent_role_creds | jq -r .Credentials.AccessKeyId)
  export AWS_SECRET_ACCESS_KEY=$(echo $agent_role_creds | jq -r .Credentials.SecretAccessKey)
  $(echo $agent_role_creds | jq -r .Credentials > $cache_file)
  echo "create aws cache at $cache_file"
}


# ===== util ======
fetchSecret() {
  (
  account_name="$1"
  secret_name="$2"
  echo $secret_name
  assume_role $(account_id_for_name ${account_name}) "DeployApp"
  echo `aws secretsmanager get-secret-value --secret-id ${secret_name} --query SecretString --output text --region ap-southeast-1`
  )
}

account_id_for_name() {
  case $1 in
    tools) echo "688318228301";;
    dev) echo "246477751131";;
    qa) echo "246477751131";;
    int) echo "246477751131";;
    uat) echo "246477751131";;
    prod) echo "315858814413";;
  esac
}

assume_role() {
  account_id="$1"
  role="$2"

  credentials=$(aws sts assume-role --role-arn "arn:aws:iam::${account_id}:role/${role}" \
                                      --role-session-name initial --duration-seconds 2700 --region ap-southeast-1 | jq '.Credentials')
  export AWS_ACCESS_KEY_ID=$(echo "${credentials}" | jq -r .AccessKeyId)
  export AWS_SECRET_ACCESS_KEY=$(echo "${credentials}" | jq -r .SecretAccessKey)
  export AWS_SESSION_TOKEN=$(echo "${credentials}" | jq -r .SessionToken)
  unset AWS_SECURITY_TOKEN
}


remote_run_on_gocd_agent_host() {
  echo "Remote run directly on gocd-agent host"
  ssh -tt -i /home/go/.ssh/local_id_rsa $HOST_MAC_SSH_USER "cd ${HOST_MAC_HOME_DIR}/godata/pipelines/autoclub_frontend ; "$@
}


# ===== main ======
list_all_helps() {
  compgen -v | egrep "^help__.*"
}

NEW_LINE=$'\n'
if type -t "task_$TASK" &>/dev/null; then
  task_${TASK} ${ARGS}
else
  echo "usage: $0 <task> [<..args>]"
  echo "task:"

  HELPS=""
  for help in $(list_all_helps)
  do

    HELPS="$HELPS    ${help/help__/} |-- ${!help}$NEW_LINE"
  done

  echo "$HELPS" | column -t -s "|"
  exit 1
fi


