# sonar server
sonar.host.url=https://sonarqube.tools.buk0.com

# must be unique in a given SonarQube instance
sonar.projectKey=mkp-line-mini

# --- optional properties ---

# defaults to project key
#sonar.projectName=My project
# defaults to not provided
#sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Defaults to .
sonar.sources=./lib
sonar.test=./test/unit_test

# Dependency-check reports
sonar.dependencyCheck.htmlReportPath=DependencyCheckerReport.html

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# Allows reuse of an existing analyzer report
sonar.dart.analysis.reportPath=tests.output

# Analyzer mode
# Can be:
# - flutter (flutter analyze) - default
# - dart (dart analyze)
# - legacy (dartanalyzer)
# sonar.flutter.analyzer.mode=

sonar.coverage.exclusions=lib/src/screens/*,lib/src/widgets/*,lib/src/shared/*,lib/src/constants/*,lib/src/local_storage/shared_preference_manager/*,lib/src/widgets/dialog_widgets/*,lib/src/widgets/snackbar_widgets/*,lib/src/configs/routes/*,lib/src/core/base/*,lib/src/core/dio/*,lib/src/core/dio/dio_utils/*,lib/src/core/dio/interceptors/*,lib/src/core/firebase_remote_config/*,lib/src/core/supfeature/*