name: commons
description: Commons Module
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter

  intl: ^0.18.1
  flutter_localization: ^0.1.14

  get: ^4.6.6
  get_it: ^7.6.4
  intl_utils: ^2.8.5
  go_router: ^12.0.0
  convert: ^3.1.1 #Require
  # Libs
  flutter_secure_storage: ^9.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  encrypt: ^5.0.3

  # Modules
  data:
    path: "../data"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

flutter_intl:
  enabled: true
  main_locale: th