name: auth
description: Auth Module
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: ">=3.13.6"

dependencies:
  flutter:
    sdk: flutter

  commons:
    path: '../../commons'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
